#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BLEApp.Resource", IsApplication=true)]

namespace BLEApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ble = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int meter_0 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int meter_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int meter_10 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int meter_100 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int meter_101 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int meter_102 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int meter_103 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int meter_104 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int meter_105 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int meter_106 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int meter_107 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int meter_108 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int meter_109 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int meter_11 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int meter_110 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int meter_111 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int meter_112 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int meter_113 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int meter_114 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int meter_115 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int meter_116 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int meter_117 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int meter_118 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int meter_119 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int meter_12 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int meter_120 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int meter_121 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int meter_122 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int meter_123 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int meter_124 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int meter_125 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int meter_126 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int meter_127 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int meter_128 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int meter_129 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int meter_13 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int meter_130 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int meter_131 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int meter_132 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int meter_133 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int meter_134 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int meter_135 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int meter_136 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int meter_137 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int meter_138 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int meter_139 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int meter_14 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int meter_140 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int meter_141 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int meter_142 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int meter_143 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int meter_144 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int meter_145 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int meter_146 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int meter_147 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int meter_148 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int meter_149 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int meter_15 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int meter_150 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int meter_151 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int meter_152 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int meter_153 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int meter_154 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int meter_155 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int meter_156 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int meter_157 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int meter_158 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int meter_159 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int meter_16 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int meter_160 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int meter_161 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int meter_162 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int meter_163 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int meter_164 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int meter_165 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int meter_166 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int meter_167 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int meter_168 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int meter_169 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int meter_17 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int meter_170 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int meter_171 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int meter_172 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int meter_173 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int meter_174 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int meter_175 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int meter_176 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int meter_177 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int meter_178 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int meter_179 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int meter_18 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int meter_180 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int meter_181 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int meter_182 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int meter_183 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int meter_184 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int meter_185 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int meter_186 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int meter_187 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int meter_188 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int meter_189 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int meter_19 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int meter_190 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int meter_191 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int meter_192 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int meter_193 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int meter_194 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int meter_195 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int meter_196 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int meter_197 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int meter_198 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int meter_199 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int meter_2 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int meter_20 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int meter_200 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int meter_201 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int meter_202 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int meter_203 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int meter_204 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int meter_205 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int meter_206 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int meter_207 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int meter_208 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int meter_209 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int meter_21 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int meter_210 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int meter_211 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int meter_212 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int meter_213 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int meter_214 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int meter_215 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int meter_216 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int meter_217 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int meter_218 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int meter_219 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int meter_22 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int meter_23 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int meter_24 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int meter_25 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int meter_26 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int meter_27 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int meter_28 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int meter_29 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int meter_3 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int meter_30 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int meter_31 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int meter_32 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int meter_33 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int meter_34 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int meter_35 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int meter_36 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int meter_37 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int meter_38 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int meter_39 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int meter_4 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int meter_40 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int meter_41 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int meter_42 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int meter_43 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int meter_44 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int meter_45 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int meter_46 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int meter_47 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int meter_48 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int meter_49 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int meter_5 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int meter_50 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int meter_51 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int meter_52 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int meter_53 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int meter_54 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int meter_55 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int meter_56 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int meter_57 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int meter_58 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int meter_59 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int meter_6 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int meter_60 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int meter_61 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int meter_62 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int meter_63 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int meter_64 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int meter_65 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int meter_66 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int meter_67 = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int meter_68 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int meter_69 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int meter_7 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int meter_70 = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int meter_71 = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int meter_72 = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int meter_73 = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int meter_74 = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int meter_75 = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int meter_76 = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int meter_77 = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int meter_78 = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int meter_79 = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int meter_8 = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int meter_80 = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int meter_81 = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int meter_82 = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int meter_83 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int meter_84 = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int meter_85 = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int meter_86 = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int meter_87 = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int meter_88 = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int meter_89 = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int meter_9 = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int meter_90 = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int meter_91 = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int meter_92 = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int meter_93 = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int meter_94 = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int meter_95 = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int meter_96 = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int meter_97 = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int meter_98 = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int meter_99 = 2130837725;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int BeaconsButton = 2131034116;
			
			// aapt resource value: 0x7f050020
			public const int Image = 2131034144;
			
			// aapt resource value: 0x7f050000
			public const int List = 2131034112;
			
			// aapt resource value: 0x7f050021
			public const int Text = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int Text1 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int Text2 = 2131034147;
			
			// aapt resource value: 0x7f050011
			public const int beaconText = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int buildingText = 2131034136;
			
			// aapt resource value: 0x7f050003
			public const int buildingsButton = 2131034115;
			
			// aapt resource value: 0x7f05001f
			public const int button1 = 2131034143;
			
			// aapt resource value: 0x7f050005
			public const int buttonStatistics = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int editText1 = 2131034119;
			
			// aapt resource value: 0x7f05001c
			public const int editText10 = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int editText11 = 2131034142;
			
			// aapt resource value: 0x7f050009
			public const int editText2 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int editText3 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int editText4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int editText5 = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int editText6 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int editText7 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int editText8 = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int editText9 = 2131034138;
			
			// aapt resource value: 0x7f050001
			public const int imageView1 = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int meterImage = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int relativeLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int textView10 = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int textView11 = 2131034141;
			
			// aapt resource value: 0x7f050008
			public const int textView2 = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int textView3 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int textView4 = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int textView5 = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int textView6 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int textView7 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int textView8 = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int textView9 = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int meterLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int metersLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int meterStats = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Beacons = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Buildings = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int DbFileName = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int Meters = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Statistics = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
